encoding: "utf-8"
timezone: Europe/Berlin
markdown: kramdown
permalink: pretty
exclude: ['README.*', 'LICENSE.txt']
keep_files: [".git"]
sass:
  sass_dir: _sass
  style: compressed

name: m1well
subtitle: Software Developer

title: m1well

robots:
  description: Michael Wellner, Software Developer
  keywords: softare, development, backend, fullstack, spring, spring boot, spring cloud, bash, database, angular
  crawl: index,follow

url: https://m1well.github.io

baseurl: '/'

avatar: "assets/images/avatar/m1well-avatar.svg"
logo: "assets/images/logo/m1well-logo.svg"
