encoding: "utf-8"
timezone: Europe/Berlin
markdown: kramdown
permalink: pretty
exclude: ['README.*', 'LICENSE.txt']
keep_files: [".git"]
sass:
  sass_dir: _sass
  style: compressed

name: m1well
subtitle: Software Developer

title: m1well

robots:
  description: Michael Wellner, Software Developer.
  keywords: softare, development, backend, spring, spring boot, spring cloud, bash, database
  crawl: index,follow

url: https://m1well.github.io

baseurl: '/'

avatar: "assets/images/avatar/m1well-avatar.png"
logo: "assets/images/logo/m1well-logo.png"

additional_html: "- Michael Wellner - <br>passionate backend software developer from the south of germany.<br>
    <u>skills:</u> backend development | scrum | microservices | databases | project management | app monitoring | scripting<br>
    <u>main technologies:</u> java | spring-boot | spring-cloud | cloud foundry | rest | sql | docker | git | bash | gradle | intellij | macos | linux<br>"
