encoding: "utf-8"
timezone: Europe/Berlin
markdown: kramdown
permalink: pretty
exclude: ['README.*', 'LICENSE.txt']
keep_files: [".git"]
sass:
    style: compressed

name: m1well
subtitle: Software Developer

title:

robots:
    description: Michael Wellner, Software Developer.
    keywords: softare, development, backend, spring, spring boot, spring cloud, bash, database
    crawl: index,follow

url: https://m1well.github.io

baseurl: '/'

avatar: "https://avatars2.githubusercontent.com/u/20413533?s=460&v=4"

links:
  - xing:
      name: Xing
      show: true
      href: https://www.xing.com/profile/Michael_Wellner5/
      icon: fab fa-xing
  - linkedin:
      name: LinkedIn
      show: true
      href: https://linkedin.com/in/michael-wellner/
      icon: fab fa-linkedin
  - twitter:
      name: Twitter
      show: true
      href: https://twitter.com/m1well
      icon: fab fa-twitter
  - github:
      name: GitHub
      show: true
      href: https://github.com/m1well
      icon: fab fa-github
  - stackoverflow:
      name: Stack Overflow
      show: true
      href: https://stackoverflow.com/u/8344100
      icon: fab fa-stack-overflow
  - email:
      name: Email
      show: true
      href: mailto:info@m1well.com
      icon: fas fa-envelope

additional_html: "- Michael Wellner - <br>passionate backend software developer from the south of germany.<br>
    <u>skills:</u> backend development | scrum | microservices | databases | project management | app monitoring | scripting<br>
    <u>main technologies:</u> java | spring-boot | spring-cloud | cloud foundry | rest | sql | docker | git | bash | gradle | intellij | macos | linux<br>"
