version: '3.5'

networks:
  m1well-jekyll-network:

services:

  m1well-jekyll-page:
    container_name: m1well-jekyll-page
    image: jekyll/jekyll:pages
    ports:
      - "4000:4000"
    volumes:
      - ".:/srv/jekyll"
    command: jekyll serve --watch --incremental
    networks:
      - m1well-jekyll-network
