services:

  m1well-jekyll-page:
    container_name: m1well-jekyll-page
    image: mrxder/jekyll-docker-arm64:latest
    ports:
      - "4000:4000"
    volumes:
      - ".:/var/jekyll"
    command: jekyll serve --watch --incremental --host=0.0.0.0
